### ISSUE TITLE
Inquiry about Graph Retrieval Framework

### ISSUE THREAD

**Issue by Jack-ZC8** [Artessay/TC-RAG#1]
I would like to express my sincere appreciation for your open-source project, TC-RAG! The innovations and implementations are truly impressive and have inspired me greatly.

Could you please let me know which framework is used in graph retrieval (HyKGE)? I would be very grateful for any relevant documentation or example code you could share.

**Comment by jiangxinke** [comment]
Hello, Jack. We use HyKGE as our graph retrieval tool. The source code and the documents of HyKGE will be available soon.  Thanks for your attention!

**Comment by jiangxinke** [comment]
We will open the source code right now. @Jack-ZC8

**Comment by jiangxinke** [comment]
Hello, @Jack-ZC8  , HyKGE is released at: https://anonymous.4open.science/r/HyKGE.
Thanks for your attention.
