### ISSUE TITLE
Inquiry About Startup Methods for Different Solutions

### ISSUE THREAD

**Issue by CC-aff** [Artessay/TC-RAG#2]
First of all, I want to express my appreciation for this open-source project!

I have some questions regarding the startup and running methods for the different models. Could you please provide detailed instructions on how to launch each model? 

Thank you for your efforts! I look forward to your response.

**Comment by Artessay** [comment]
Thank you for your interest and appreciation of our project! We are currently working on updating the README to include detailed instructions on how to start up and run each model. We expect to complete these updates within this week. Please stay tuned for these updates. Thank you!

**Comment by jiangxinke** [comment]
> First of all, I want to express my appreciation for this open-source project!
> 
> I have some questions regarding the startup and running methods for the different models. Could you please provide detailed instructions on how to launch each model?
> 
> Thank you for your efforts! I look forward to your response.

We have updated the README.md, please feel free to launch each model.

**Comment by Artessay** [comment]
> First of all, I want to express my appreciation for this open-source project!
> 
> I have some questions regarding the startup and running methods for the different models. Could you please provide detailed instructions on how to launch each model?
> 
> Thank you for your efforts! I look forward to your response.

Hello @CC-aff ,

Thank you so much for your kind words and for your interest in our open-source project. We truly appreciate your support!

Regarding your questions about how to start up and run the different models, we've added detailed instructions to the README file. Please feel free to check it out for step-by-step guidance.

If you have any further questions or need assistance, please don't hesitate to reach out. We're always here to help.

Thanks again for your support, and we look forward to your continued involvement with the project!
