### ISSUE TITLE
When open source the code and documents of HyKGE?

### ISSUE THREAD

**Issue by Skylyong** [Artessay/TC-RAG#5]
Great work. When will you open source the code and the documents of HyKGE? Can you give me a specific time?

**Comment by jiangxinke** [comment]
Hello, Skylyong. 

We plan to update the source code of HyKGE right now. The KG data will be open-sourced after we solve the copyright problem. But we will open some samples to execute the source code.

**Comment by jiangxinke** [comment]
Hello, @Skylyong , HyKGE is released at: https://anonymous.4open.science/r/HyKGE.
Thanks for your attention.
